# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20180614_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('L', 'Liked'), ('C', 'Commented'), ('F', 'Favorited'), ('E', 'Edited Article'), ('A', 'Also Commented'), ('S', 'Shared'), ('I', 'Logged In'), ('O', 'Logged Out')], max_length=1),
        ),
    ]
