# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20180321_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_url',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_youtube_embed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
