# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-17 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20180113_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='shared_feed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SharedFeed+', to='feeds.Feed'),
        ),
        migrations.AddField(
            model_name='feed',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
